import keyMirror from 'mirrorkey'

export default keyMirror({
    GET_CHART: null,
    GET_CHART_PENDING: null,
    GET_CHART_SUCCESS: null,
    GET_CHART_ERROR: null,

    GET_HOTEL: null,
    GET_HOTEL_PENDING: null,
    GET_HOTEL_SUCCESS: null,
    GET_HOTEL_ERROR: null,

    GET_GLOBAL_DATA: null,
    GET_GLOBAL_DATA_PENDING: null,
    GET_GLOBAL_DATA_SUCCESS: null,
    GET_GLOBAL_DATA_ERROR: null,

    GET_STATIS_DATA: null,
    GET_STATIS_DATA_PENDING: null,
    GET_STATIS_DATA_SUCCESS: null,
    GET_STATIS_DATA_ERROR: null,

    GET_TREND_DATA: null,
    GET_TREND_DATA_PENDING: null,
    GET_TREND_DATA_SUCCESS: null,
    GET_TREND_DATA_ERROR: null,

    GET_GOODS_VIEW_DATA: null,
    GET_GOODS_VIEW_DATA_PENDING: null,
    GET_GOODS_VIEW_DATA_SUCCESS: null,
    GET_GOODS_VIEW_DATA_ERROR: null,

    GET_GOODS_PAY_DATA: null,
    GET_GOODS_PAY_DATA_PENDING: null,
    GET_GOODS_PAY_DATA_SUCCESS: null,
    GET_GOODS_PAY_DATA_ERROR: null,

    GET_GOODS_AMOUNT_DATA: null,
    GET_GOODS_AMOUNT_DATA_PENDING: null,
    GET_GOODS_AMOUNT_DATA_SUCCESS: null,
    GET_GOODS_AMOUNT_DATA_ERROR: null
})
